### PR TITLE
Neubias biii search

### PR DESCRIPTION
**Pull request by haesleinhuepf**
Hey @ctrueden,
CC @frauzufall,

I was just working on the NEUBIAS BIII.eu search plugin for Fiji, together with @PerrineGilloteaux (she programmed the server side). We tested it successfully carfully and would like to merge it into Fiji core.

Do you think it's fine merging thse changes?

Thanks a lot!

Cheers,
Robert

### CODE REVIEW

**Comment by ctrueden** [comment]
Thanks for working on this.

To maintain good separation of concerns and clean dependencies, I'd like to put this component in its own component: `imagej/imagej-plugins-search-bise`. The reason I suggest to put it in the `imagej` org rather than `scijava` is because BISE is image-specific, whereas SciJava is for libraries and plugins more general than only images.

**Comment by haesleinhuepf** [comment]
Hi @ctrueden,

I'm happy to put it in a separate repository. Just saying: BIII.eu is not ImageJ specific:

http://biii.eu/scijava
http://biii.eu/search?search_api_fulltext=cell+profiler
http://biii.eu/search?search_api_fulltext=knime

Cheers,
Robert

**Comment by haesleinhuepf** [comment]
Shall we make it part of the Fiji distribution / github organisation?

**Comment by imagejan** [comment]
@haesleinhuepf wrote:
> BIII.eu is not ImageJ specific

True, it's not ImageJ-specific, but it's image-specific. I agree with @ctrueden that it best fits in the `imagej` org (as it integrates an image-related search into the SciJava search) rather than the `scijava` org.

**Pull request closed without merging**
